### ISSUE TITLE
Tracking issue to merge ZeroMQ-NG back into ZeroMQ.js

### ISSUE THREAD

**Issue by rolftimmermans** [zeromq/zeromq.js#347]
- [x] Merge ZeroMQ-NG into ZeroMQ.js
  - [x] Create zeromq.js@5.x branch for bugfixes
  - [x] [PR to zeromq.js@master that brings in zeromq-ng](https://github.com/zeromq/zeromq.js/pull/343)
  - [x] Check that PR doesn't include any version tags
  - [x] Fix CI (Travis only, AppVeyor is no longer needed)
  - [ ] Provide access to integration users for Github & NPM **[waiting for feedback](https://github.com/zeromq/zeromq.js/pull/343#issuecomment-544469362)**
  - [ ] Add encrypted API keys for Github & NPM to .travis.yml
  - [ ] Await review from all maintainers  **[waiting for feedback](https://github.com/zeromq/zeromq.js/pull/343#issuecomment-544469362)**
  - [ ] Merge PR into master
  - [ ] Turn off AppVeyor checks for the master branch
- [ ] Release v6.0.0-beta.1
  - [ ] Tag v6.0.0-beta.1 and wait for prebuilds & deployment to NPM
  - [ ] Release ZeroMQ-NG with a wrapper around the new ZeroMQ.js beta
  - [ ] Point users of ZeroMQ-NG to ZeroMQ.js in its README
  - [ ] Submit PR to https://github.com/DefinitelyTyped/DefinitelyTyped to deprecate the old manual types as of v6.0.0-beta.1
  - [ ] Encourage people on all issues to try the new beta and see if there are any blockers
- [ ] Release v6.0.0
  - [ ] Deprecate zeromq@5.x
  - [ ] Publish zeromq@6.0.0 to npm once we feel ready

**Comment by rolftimmermans** [comment]
The beta is out! I'll go through some older issues to see if they are fixed by the beta and encourage people to try it out. I'll be monitoring new issues coming.

**Comment by zorro-fr24** [comment]
Superb work @rolftimmermans! - we've been holding our breath for this merge for a long long time. I look forward to rolling this back into our stack in the near future.

**Comment by rolftimmermans** [comment]
I have gone through all issues and commented on & closed the ones that I know have been addressed with the 6.0 rewrite. Remaining issues are either build issues (mostly related to Electron) or issues that I have trouble reproducing; on the last category I have left comments asking reporters to try out 6.0.

I have added a few labels to make it a bit easier to identify the current issue status & version to which it applies.

Someone else might have to look at the Electron issues because that is far outside my area of expertise (6.0 does include Electron prebuilds for all supported platforms, generated by [prebuildify](https://github.com/prebuild/prebuildify)).
